---
# tasks file for my_apache
- package:
    name: "httpd"
    state: present

- service:
    name: "httpd"
    state: started
  notify: enable apache

#- service:
#    name: "httpd"
#    enabled: yes


- name: create index page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache


- name: Include servise vars
  include_vars:
    file: services.yml
    name: services

- name: start firewall
  service:
    name: "firewalld"
    state: started

- name: enable firewall
  service:
    name: "firewalld"
    enabled: yes

#  notify: restart firewall

- name: open ports
  command: firewall-cmd --zone=public --add-service={{ item.value.name }} --permanent
  args:
    warn: false
  loop: "{{ lookup('dict', services) }}"
  notify: restart firewall

- command: service httpd status
  args:
    warn: false
